server:
    port: 8082

dubbo:
    application:
        name: dubbo-consumer
    registry:
        protocol: zookeeper
        address: docker.local:2181
        timeout: 30000
    protocol:
        name: dubbo
        port: 20881
    provider:
        timeout: 6000
        cluster: failfast
        retries: 0
    consumer:
        check: false
        timeout: 6000
