server:
    port: 8081

dubbo:
    application:
        name: dubbo-provider
    registry:
        protocol: zookeeper
        address: docker.local:2181
        timeout: 30000
    protocol:
        name: dubbo
        port: 20880
        status: server
    provider:
        timeout: 6000
        cluster: failfast
        retries: 0
    consumer:
        check: false
        timeout: 6000
